import type { Metadata } from "next";
import "./globals.css";
import RealTimeNotificationManager from "../shared/components/common/notify/RealTimeNotificationManager";
import WebSocketInitializer from "../shared/lib/WebSocketInitializer";
import { AuthProvider } from '../context/AuthContext';
import { MemberTypeProvider } from '../context/MemberTypeContext';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="antialiased" suppressHydrationWarning={true}>
        <AuthProvider>
          <MemberTypeProvider>
            <main>{children}</main>
            <RealTimeNotificationManager />
            <WebSocketInitializer />
          </MemberTypeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
