# fly.toml app configuration file generated for nbe6-8-3-team11 on 2025-08-28T11:14:36+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nbe6-8-3-team11'
primary_region = 'nrt'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  SPRING_PROFILES_ACTIVE = "fly"
  PORT = "8080"

[checks]
  [checks.health]
    type = "http"
    port = 8080
    method = "get"
    path = "/actuator/health"
    timeout = "30s"
    interval = "60s"  
    grace_period = "60s"
