package com.back.domain.notification.enums

enum class NotificationType {
    ADOPTION_REQUESTED, ADOPTION_ACCEPTED, ADOPTION_REJECTED,
    CARE_REQUESTED, CARE_ACCEPTED, CARE_REJECTED, NEW_MESSAGE, CHAT_ROOM_DELETED
}
