spring:
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: false
  sql:
    init:
      mode: always

  # Redis 설정
  data:
    redis:
      host: localhost
      port: 6379
      password: # Redis 비밀번호가 설정되어 있다면 여기에 입력
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms