spring:
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

# 채팅 기능 활성화 (개발 환경)
chat:
  enabled: true