spring:
  datasource:
    url: jdbc:h2:mem:db_test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: test-client-id
            client-secret: test-client-secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            scope:
              - profile_nickname
              - account_email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: 'MyTestJwtSecretKeyIsVeryVeryLongAndAbsolutelySecureForTestingPurpose'
  access-token-expiration: PT10M
  refresh-token-expiration: PT1H
